api:
  replicas: 2
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    className: gce
    annotations:
      kubernetes.io/ingress.allow-http: "false"
    hosts:
      - host: api-loadtest.example.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - api-loadtest.example.com
        secretName: api-tls-cert
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 2Gi

worker:
  replicas: 2
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 2Gi

otelCollector:
  enabled: true
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
        path: /health/status
    processors:
      batch:
    exporters:
      googlecloud:
        project: ${env:GOOGLE_CLOUD_PROJECT}
    service:
      extensions: [health_check]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [googlecloud]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [googlecloud]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [googlecloud]
