apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - namespace.yaml
  - helmrelease.yaml
configMapGenerator:
  - name: tx-agent-kit-images
    files:
      - values.yaml=images.values.yaml
generatorOptions:
  disableNameSuffixHash: true
