apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: tx-agent-kit-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/Just-Understanding-Data-Ltd/tx-agent-kit.git
  ref:
    branch: main
