apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tx-agent-kit-gke-staging
  namespace: flux-system
spec:
  interval: 1m
  prune: true
  wait: true
  timeout: 10m
  path: ./deploy/gitops/environments/gke-staging
  sourceRef:
    kind: GitRepository
    name: tx-agent-kit-repo
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tx-agent-kit-gke-prod
  namespace: flux-system
spec:
  interval: 1m
  prune: true
  wait: true
  timeout: 10m
  path: ./deploy/gitops/environments/gke-prod
  sourceRef:
    kind: GitRepository
    name: tx-agent-kit-repo
