apiVersion: v1
kind: Service
metadata:
  name: {{ include "tx-agent-kit.fullname" . }}-api
  labels:
    {{- include "tx-agent-kit.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "tx-agent-kit.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      {{- if and (eq .Values.api.service.type "NodePort") .Values.api.service.nodePort }}
      nodePort: {{ .Values.api.service.nodePort }}
      {{- end }}
