{{- if not .Values.runtimeEnvSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tx-agent-kit.runtimeSecretName" . }}
  labels:
    {{- include "tx-agent-kit.labels" . | nindent 4 }}
type: Opaque
{{- if .Values.runtimeEnv }}
stringData:
  {{- $runtimeEnv := .Values.runtimeEnv }}
  {{- range $key := keys $runtimeEnv | sortAlpha }}
  {{ $key }}: {{ index $runtimeEnv $key | quote }}
  {{- end }}
{{- else }}
stringData: {}
{{- end }}
{{- end }}
